### ISSUE TITLE
Fix dependence on ambient default agent pool in arcade-powered source-build AzDO templates

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1795]
@brettfo encountered an issue in https://github.com/dotnet/fsharp/pull/10243 where the arcade-powered sb template tried to use an old Windows agent to run our Docker containers for source-build, which failed, but the same template usage got a Linux agent and worked in dotnet/source-build-reference-packages.

I think the cause is the default pool here:

![sbrp](https://user-images.githubusercontent.com/12819531/95781919-5a067d80-0c94-11eb-85c6-ebc47c952c21.png)

vs. fsharp:

![fsharp](https://user-images.githubusercontent.com/12819531/95781936-625eb880-0c94-11eb-9d58-9b6363133be2.png)

I think the right fix is to always specify a pool here, so we don't depend on the ambient default (from the AzDO pipeline definition in this case, but a `stage` could also cause this I think):

https://github.com/dotnet/arcade/blob/abf9263d1fe9eb075cb5f9d117c9e36668b99408/eng/common/templates/job/source-build.yml#L38-L41

Something like this:

```yaml
  ${{ if ne(parameters.platform.container, '') }}:
    container: ${{ parameters.platform.container }}
    pool: ${{ coalesce(parameters.platform.containerHost, parameters.defaultContainerHostPool) }}
```
