### ISSUE TITLE
source-build-sdk-diff-tests pipeline is running too often

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3407]
The source-build-sdk-diff-tests are running on a schedule for the release branch that have already been released.  This pipeline should only be running on the "active" branches.

This is a waste of build agent compute.

**Comment by MichaelSimons** [comment]
FYI @premun - not sure how to solve this without introducing a maintenance burden.

**Comment by premun** [comment]
@MichaelSimons I was checking if maybe us going to the UI and overriding this would work for us and noticed a new setting that says "only run when source code / pipelines changed". I think this is exactly what we'd like we only need to backport this into the preview3 branches.

However, I checked the YAML docs and it says the default is to not run:
```yaml
schedules:
- cron: string # cron syntax defining a schedule
  displayName: string # friendly name given to a specific schedule
  branches:
    include: [ string ] # which branches the schedule applies to
    exclude: [ string ] # which branches to exclude from the schedule
  always: boolean # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.
```

Maybe the docs are wrong and we could explicitly set `false`. I will try that.
