### ISSUE TITLE
Add CI for Fedora legs (Azure DevOps)

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#814]
The docker image doesn't have pkill and hangs during smoke-test.

```yaml
- template: ../phases/ci-linux.yml
  parameters:
    phase: fedora28
    imageName: microsoft/dotnet-buildtools-prereqs:fedora-28-c103199-20180628122443
    matrix:
      Production: {}
      Online: { type: Online }
      Online Portable: { type: Online Portable }
      Offline: { type: Offline }
      Offline Portable: { type: Offline Portable }
```

Pulled out from https://github.com/dotnet/source-build/pull/813.
