### ISSUE TITLE
Add CI for Debian 8.2 legs (Azure DevOps)

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#815]
CoreFX native build can't find `libgssapi_krb5`, suggests installing `libkrb5-dev`.

```yaml
- template: ../phases/ci-linux.yml
  parameters:
    phase: debian82
    imageName: microsoft/dotnet-buildtools-prereqs:debian-8.2-c103199-20180628122423
    matrix:
      Production: {}
      Online: { type: Online }
      Offline: { type: Offline }
```

Pulled out from https://github.com/dotnet/source-build/pull/813.
